### PR TITLE
Clarify PHP versions

### PR DESCRIPTION
**Pull request by dereuromark**
right now people dont know until they tried.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Thanks, I did see 'chose' instead of 'choose'. Do you want to correct or shall I just merge?

**Comment by dereuromark** [comment]
Fixed :) Thx!

**Comment by bravo-kernel** [comment]
Thank you 👍

**Comment by dereuromark** [comment]
And I can confirm the installer works (selected PHP 7.2) and all good.
It just didnt use my Cakebox.yaml config then (empty Apps dir) for some reason.
Not sure what went wrong there after vagrant reload.

**Pull request merged**
