### PR TITLE
Fix TLD

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/alt3/cakebox/issues/63
Anything else?

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Branch will always fail so no problem, there are more references to `.app` in the readthedocs `/docs` directory though. Those should also be updated for consistency. Do a search for `.app` in this repo to spot them.

**Comment by dereuromark** [comment]
Maybe someone has time to help complete this?

**Comment by bravo-kernel** [comment]
Not until next month. There are not many refs so if somebody wants to jump in:

https://github.com/alt3/cakebox/search?utf8=%E2%9C%93&q=.app

**Comment by bravo-kernel** [comment]
Closing as there seems to be no interest solving this.

**Pull request closed without merging**
