### PR TITLE
logging added to bash files and logs appended to /var/log/cakephp/cak…

### PR DESCRIPTION
**Pull request by Modicrumb**
Created for issue https://github.com/alt3/cakebox/issues/47

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Appreciated, will try to test this weekend using a fresh install.

**Comment by bravo-kernel** [comment]
Just checked and the box comes up as expected (with logging as shown below).

However, like you pointed out the format is not in `LogStash` format and thus the entries do not appear in ElasticSearch and/or Kibana (second screenshot). 

Any chance the format can be changed to use LogStash? 
 
```bash
[Fri Feb  9 08:28:33 UTC 2018] [DEBUG]  < check-ssh-agent SCRIPTEXIT
[Fri Feb  9 08:28:34 UTC 2018] [DEBUG]  > console-installer SCRIPTENTRY
[Fri Feb  9 08:28:34 UTC 2018] [INFO]  Please wait... installing Cakebox Commands and Dashboard
[Fri Feb  9 08:28:41 UTC 2018] [INFO]  * Updating Composer cache permissions
[Fri Feb  9 08:28:41 UTC 2018] [INFO]  * Creating project
[Fri Feb  9 08:29:56 UTC 2018] [INFO]  * Composer installing
[Fri Feb  9 08:33:24 UTC 2018] [INFO]  Installation completed successfully!
[Fri Feb  9 08:33:24 UTC 2018] [DEBUG]  < console-installer SCRIPTEXIT
{"@timestamp":"2018-02-09T08:33:27.387032+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"================================================================================","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:27.387621+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"Self-updating cakebox","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:27.387720+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":200,"ctxt_scope":[]},"@message":"Self-updating Composer","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:27.387843+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"Shell command as root:`sudo composer self-update 2>&1`","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.815774+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"* Shell output:","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.815962+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"  => You are running composer as \"root\", while \"/home/vagrant/.composer\" is owned by \"vagrant\"","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816049+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"  => Updating to version 1.6.3 (stable channel).","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816129+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"  =>    Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)         \b\b\b\b\b\b\b\b\b","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816203+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"  => Use composer self-update --rollback to return to version 3c09c0ab2a4b1acc13807fb7ff012a18d67a3a38","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816277+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"* Shelled command completed successfully","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816410+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":200,"ctxt_scope":[]},"@message":"* Updating cache permissions","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.816984+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"Shell command as root:`sudo chown vagrant:vagrant /home/vagrant/.composer -R 2>&1`","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.832061+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"* Shelled command completed successfully","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.832253+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":200,"ctxt_scope":[]},"@message":"Updating Cakebox Commands and Dashboard","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.835701+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":200,"ctxt_scope":[]},"@message":"* Detecting branch","@tags":["cli.cakebox"],"@type":"cakephp"}
{"@timestamp":"2018-02-09T08:33:28.836148+00:00","@source":"cakebox","@fields":{"channel":"cli.cakebox","level":100,"ctxt_scope":[]},"@message":"Shelling command `sudo su vagrant -c \"cd /cakebox/console; git rev-parse --abbrev-ref HEAD\"` as user `vagrant`","@tags":["cli.cakebox"],"@type":"cakephp"}
```

image

**Comment by Modicrumb** [comment]
Yeah I would just have to change logger.sh logic, give me a week or so and I'll get this in.

**Comment by bravo-kernel** [comment]
That would be more than nice. No rush, these things take time.

Sent from my Mobile Device

**Comment by Modicrumb** [comment]
Updated this PR, Logger now logs in LogStash format

**Comment by bravo-kernel** [comment]
Thanks, I will spin up a new box this weekend to test.

**Comment by bravo-kernel** [comment]
Just tested mr. @Modicrumb and.. the log entries are now appearing in ElasticSearch/Kibana.

Job well done, much obliged 💯 

image

**Pull request merged**
